#!/bin/sh

for s in log/*.c
do
  base=`basename $s .c`
  gcc -o log/${base}.exe log/$base.c
  ./runlim \
    -o log/$base.log \
    -s 5 \
    -t 5\
    ./log/${base}.exe 1>log/$base.out 2>log/$base.err
done
