name: Tests

on:
  push:
    branches: [ $default-branch, "devel" ]
  pull_request:
    branches: [ $default-branch, "devel" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure.sh
    - name: make
      run: make -j
    - name: make tests
      run: make tests -j
    - name: execute tests in junit format
      run: ./tests --reporter junit
